### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by Ouwen** [MyWhiteCastle/BME-590-Project3#1]
1. README.md
 - Results: caption of what the results show

2. Getting started / organization of repo
 - Which models were used to generate the figure?
 	- keras default
 	- pruned (70% sparsity)

3.
 - Organize models into a folder
 - List the most impressive model and provide the sparsity

 - List out all models tested
 - Delete redundant models

4. Add a Thanks / Reference
 - paper
 - code
 - classes

5. Add a License
 - MIT
 - APACHE 2.0

6. Explain in your own words
Pruning
Iter pruning
Quantization
Huffman

**Comment by MyWhiteCastle** [comment]
Updated
